# Generated by Django 4.1.3 on 2022-11-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FinalControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tests/images/')),
                ('ans', models.CharField(max_length=500)),
                ('ans1', models.CharField(max_length=500)),
                ('ans2', models.CharField(max_length=500)),
                ('ans3', models.CharField(max_length=500)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_control.lesson')),
            ],
        ),
    ]
