# Generated by Django 4.1.3 on 2022-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_control', '0002_controltest_usercontroltestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltest',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
