# Generated by Django 4.1.3 on 2022-11-21 12:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Variant')),
                ('is_true', models.BooleanField(default=False, verbose_name="To'g'ri yoki xatoligi")),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules', verbose_name='Rasm')),
                ('name', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes', verbose_name='Mavzu')),
                ('title', models.CharField(max_length=500, verbose_name='Nomi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Mavzu tartib raqami')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Mazmuni')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Savol matni')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Savol tartib raqami')),
                ('answers', models.ManyToManyField(to='modul.answer', verbose_name='Variantlar')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.theme', verbose_name='Mavzuni tanlang')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['order'],
            },
        ),
    ]
