# Generated by Django 4.1.3 on 2022-11-21 12:30

from django.db import migrations, models
import django.db.models.deletion
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes', verbose_name='Rasm')),
                ('title', models.CharField(max_length=500, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=200, verbose_name='Kitob muallifi')),
                ('file', models.FileField(upload_to='books', validators=[home.validators.validate_file_extension], verbose_name='Kitob fayli')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Kitob url manzili')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='IncomingMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternetResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes', verbose_name='Resurs rasmi')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('content', models.CharField(max_length=500, null=True, verbose_name='Qisqacha')),
                ('url', models.URLField(verbose_name='Resurs url manzili')),
            ],
            options={
                'verbose_name': 'Internet resurs',
                'verbose_name_plural': 'Internet resurslar',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False, verbose_name="So'rovnoma holati")),
                ('title', models.CharField(max_length=500, verbose_name="So'rovnoma savoli")),
                ('ans1', models.CharField(max_length=200, verbose_name='Variant')),
                ('ans2', models.CharField(max_length=200, verbose_name='Variant')),
                ('ans3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant')),
                ('ans4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant')),
                ('ans5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant')),
                ('ans6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant')),
                ('res1', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('res2', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('res3', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('res4', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('res5', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('res6', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='YouTube ifareme')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.videocategory')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
            },
        ),
    ]
